network:
  version: 2
  renderer: networkd
  ethernets:
    enp5s0:
      dhcp4: true
    enp7s0:
      dhcp4: false
      addresses:
        - 192.168.1.20/24
      gateway4: 192.168.1.254
      nameservers:
        addresses:
          - 192.168.1.254
