---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /PoolA/video/library:/config
      - /PoolA/video/tv:/tv
      - /PoolA/video/movies:/movies
    restart: unless-stopped
