---
- hosts: all
  become: yes
  tasks:
    - name: apt update
      apt:
        name:
          - lm-sensors
          - hddtemp
          - zfsutils-linux
          - docker-compose
        update_cache: yes
        cache_valid_time: 3600

    - name: apt dist-upgrade
      apt:
        upgrade: dist

#    - name: Copy netplan
#      ansible.builtin.copy:
#        src: 01-netplan.yaml
#        dest: /etc/netplan/01-netplan.yaml
#        owner: root
#        group: root
#        mode: '0644'

    - name: Copy docker-compose.yml file
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: /home/will/docker-compose.yml
        owner: will
        group: will
        mode: '0644'

    - name: Add Will to the docker group
      ansible.builtin.user:
        name: will
        shell: /bin/bash
        append: yes
        groups: docker
